server:
  port: 7060

spring:
  application:
    name: request
  profiles:
    active: test #always use profile 'test' to pass github pr build. Locally 'local' can be used
  datasource:
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
