server:
  port: 8888

spring:
  application:
    name: config-server
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


