server:
  port: 6060

spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
